### ISSUE TITLE
error ❌ headers.set is not a function

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink#15]
Using in https://github.com/pinax-network/substreams-sink-webhook

```typescript
    // User parameters
    const outputModule = options.moduleName;
    const startBlockNum = options.startBlock;
    const stopBlockNum = options.stopBlock;
    const params = options.params;
    const headers = options.headers;
    const cursorPath = options.cursorPath;
    const productionMode = !options.disableProductionMode;
    // Adding default headers
    headers.set("User-Agent", "substreams-sink");
```

```
> substreams-sink-webhook@0.3.5 start
> tsc && node --no-warnings ./dist/bin/cli.js run

file:///Users/denis/Github/substreams-sink-webhook/node_modules/substreams-sink/dist/src/setup.js:33
    headers.set("User-Agent", "substreams-sink");
            ^

TypeError: headers.set is not a function
    at setup (file:///Users/denis/Github/substreams-sink-webhook/node_modules/substreams-sink/dist/src/setup.js:33:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.action (file:///Users/denis/Github/substreams-sink-webhook/dist/index.js:9:37)

Node.js v20.5.0
```

**Comment by chamorin** [comment]
Fixed in commit: https://github.com/pinax-network/substreams-sink/commit/588865b71ea20593e3359b502c20f4f7c013294e

**Comment by DenisCarriere** [comment]
Fixed
